# Generated by Django 4.1.4 on 2022-12-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choise_text',
            new_name='choice_text',
        ),
    ]
